apiVersion: apps/v1
kind: Deployment
metadata:
  name: fate-no-bot
  labels:
    app: fate-no-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fate-no-bot
  template:
    metadata:
      labels:
        app: fate-no-bot
    spec:
      containers:
        - name: fate-no-bot
          image: registry.gitlab.com/fullpipe/registry/fate_no_bot:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fate-no-bot
      imagePullSecrets:
        - name: gitlab-registry-secret
